### ISSUE TITLE
刷新后页面没有内容

### ISSUE THREAD

**Issue by kcmeven** [bailihuiyue/ant-design-pro-tabs#2]
刷新后页面没有内容，是这个组件的问题，还是我这边代码的问题呢

**Comment by bailihuiyue** [comment]
你好,可以提供更详细的信息吗

**Comment by CooderHYLee** [comment]
![671585818144_ pic_hd](https://user-images.githubusercontent.com/16789238/78230310-bd546d80-7503-11ea-972a-33bd60cdad38.jpg)
刷新后，name出错了
