### ISSUE TITLE
clone下来正常，怎么迁移到4.0的BasicLayout.tsx上

### ISSUE THREAD

**Issue by liuyouying** [bailihuiyue/ant-design-pro-tabs#3]
大神你好，我下了您的代码跑起来了，但2.0和4.0代码完全不一样了，不知怎么挪过去，是否有4.0的demo？
不知怎么联系您，readme说的QQ和邮箱也没找到，希望在这留言能看到
也怪了，多标签页这么重要的特性，为什么网上都没有AntD的案例，还是说我搜索姿势不对？

**Comment by bailihuiyue** [comment]
老铁，按照readme做就行了，多标签那个组件是单独的，从项目中考出来就行了，我的qq：964981348，你是联系的这个么，这个特性我看过ant pro的官方，他们也不打算去做，网上也很少有人做，于是我就做了一个

**Comment by bailihuiyue** [comment]
> 大神你好，我下了您的代码跑起来了，但2.0和4.0代码完全不一样了，不知怎么挪过去，是否有4.0的demo？
> 不知怎么联系您，readme说的QQ和邮箱也没找到，希望在这留言能看到
> 也怪了，多标签页这么重要的特性，为什么网上都没有AntD的案例，还是说我搜索姿势不对？

老铁，按照readme做就行了，多标签那个组件是单独的，从项目中考出来就行了，我的qq：964981348，你是联系的这个么，这个特性我看过ant pro的官方，他们也不打算去做，网上也很少有人做，于是我就做了一个

**Comment by liuyouying** [comment]
> > 大神你好，我下了您的代码跑起来了，但2.0和4.0代码完全不一样了，不知怎么挪过去，是否有4.0的demo？
> > 不知怎么联系您，readme说的QQ和邮箱也没找到，希望在这留言能看到
> > 也怪了，多标签页这么重要的特性，为什么网上都没有AntD的案例，还是说我搜索姿势不对？
> 
> 老铁，按照readme做就行了，多标签那个组件是单独的，从项目中考出来就行了，我的qq：964981348，你是联系的这个么，这个特性我看过ant pro的官方，他们也不打算去做，网上也很少有人做，于是我就做了一个

多谢答复，近期在忙其它项目暂时没空研究，后面打算下个全家桶，直接用别人的好了

**Comment by bailihuiyue** [comment]
> > > 大神你好，我下了您的代码跑起来了，但2.0和4.0代码完全不一样了，不知怎么挪过去，是否有4.0的demo？
> > > 不知怎么联系您，readme说的QQ和邮箱也没找到，希望在这留言能看到
> > > 也怪了，多标签页这么重要的特性，为什么网上都没有AntD的案例，还是说我搜索姿势不对？
> > 
> > 
> > 老铁，按照readme做就行了，多标签那个组件是单独的，从项目中考出来就行了，我的qq：964981348，你是联系的这个么，这个特性我看过ant pro的官方，他们也不打算去做，网上也很少有人做，于是我就做了一个
> 
> 多谢答复，近期在忙其它项目暂时没空研究，后面打算下个全家桶，直接用别人的好了

如果发现了更好的多标签项目,也告诉我一下,我也开拓一下思路
